### ISSUE TITLE
PDF SET PAGE ROTATION2 not found

### ISSUE THREAD

**Issue by Znogoudu** [miyako/4d-plugin-pdf-kit#1]
Hello, 
I have installed the plugin on a 4D server (4Dv13) with the V11 version of the plugin to fix el capitan issue. The server is on OS X 10.9 and the other stations on El Capitan or 10.6.
The method PDF SET PAGE ROTATION is present and working but I can't find the method PDF SET PAGE ROTATION2.
![capture d ecran 2016-05-12 a 09 25 27](https://cloud.githubusercontent.com/assets/19321360/15207023/8687c05e-1823-11e6-995c-4aaab3bfccfd.png)

**Comment by miyako** [comment]
"PDF SET PAGE ROTATION2" 
look at the documentation, there is not such command.
I don't understand, what are you trying to do?

The "fix for El Capitan" is done at the "C" level, 
you don't have to do anything in 4D.

https://github.com/miyako/4d-plugin-pdf-kit/blob/master/PDF%20Kit/4DPlugin.cpp

**Comment by Znogoudu** [comment]
I try to rotate a PDF, it works on OS X 10.6 but it doesn't on El Capitan. 
I understood I have to call the PDF SET PAGE ROTATION2 method on 4D to rotate the PDF on El capitan.

**Comment by miyako** [comment]
Did you download and use the latest version?

**Comment by Znogoudu** [comment]
yes, I use the V11 version of the PDF Kit 1.2

**Comment by miyako** [comment]
I've recompiled and copied the sample form from the v14/15 example to v11. seems to work.
(I didn't test with v11-13 on El Capitan, that combination of 4D is not supported)

**Comment by Znogoudu** [comment]
It works ! thank you.
