### ISSUE TITLE
Fuite mémoire

### ISSUE THREAD

**Issue by MatthieuLamp** [miyako/4d-plugin-pdf-kit#3]
Hi,
J’utilise votre plugin PDF Kit avec 4D 20R4 sur macOS 14 et je rencontre un problème de fuite mémoire.

Si vous appelez la commande, par exemple, PDF GET PAGE, dans le Process principal, la mémoire utilisée par 4D augmente, et ne redescend pas !

Voici une base exemple
[pdf.zip](https://github.com/user-attachments/files/16100004/pdf.zip)

**Comment by MatthieuLamp** [comment]
screen capture

https://github.com/miyako/4d-plugin-pdf-kit/assets/48675663/6b37cbc3-703b-4220-9493-b0dfa210a1e6

**Comment by miyako** [comment]
seen in Xcode.

* memory usage increasing while process is running, recovers when process ends. this is normal, for auto release pool
* memory usage increases when 4D opens a project, launches a process. the base line is stable and decreases when the project is closed

<img width="752" alt="memory" src="https://github.com/miyako/4d-plugin-pdf-kit/assets/1725068/ebd60ad6-93e6-43ff-a2a5-7c57b55e0244">

**Comment by miyako** [comment]
## about the `PDF_GET_PAGE` command

it is not using *PDfKit*, it is actually a `CGPDF` polyfill

* `CGDataProviderCreateWithData` - paired with `CGDataProviderRelease`
* `CGPDFDocumentCreateWithProvider` - paired with `CGPDFDocumentRelease`
*  `CGPDFDocumentGetPage` - autorelease
* `CGDataConsumerCreateWithCFData` - paired with `CGDataConsumerRelease`
* `CGPDFContextCreate` - paired with `CGContextRelease`
* `PDFDocument.pageAtIndex` - autorelease

**Comment by miyako** [comment]
effect of autoreleasepool

* the temporary spike in memory usage while running a loop in a process is avoided
* the overall memory consumption doesn't change
 
<img width="763" alt="memory" src="https://github.com/miyako/4d-plugin-pdf-kit/assets/1725068/eede166d-45a9-4905-a94b-7b752179a745">

**Comment by miyako** [comment]
https://github.com/miyako/4d-plugin-pdf-kit/releases/tag/2.2.0

**Comment by MatthieuLamp** [comment]
it's ok ! 
thanks !
