### ISSUE TITLE
version 2.2.0 non signée

### ISSUE THREAD

**Issue by MatthieuLamp** [miyako/4d-plugin-pdf-kit#4]
Hi

La version 2.2.0 n'est pas signée sur macOS
<img width="416" alt="Capture d’écran 2024-07-05 à 10 06 22" src="https://github.com/miyako/4d-plugin-pdf-kit/assets/48675663/e9e2d3c8-3274-42ce-b8f2-337336c48376">

**Comment by miyako** [comment]
please download again

**Comment by MatthieuLamp** [comment]
it's ok 
La version indiquée est 2.1, or c'est 2.2
<img width="510" alt="Capture d’écran 2024-07-05 à 19 36 34" src="https://github.com/miyako/4d-plugin-pdf-kit/assets/48675663/3425bea7-1870-442e-8cbd-33e0731bbed7">
